# Workflow for MIPT TP course

name: CI

# Run actions on master commit / pull request
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# Jobs setup
jobs:
  # Main build and test job
  build-and-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
      with: 
        repository: 'google/googletest'
        path: '${{github.workspace}}/TechProgCITemplate/3rdparty/' 
    - run: mkdir ci_build
    - name: Build
      run: echo Hello, world!
    
    - name: 'Run CMake with Ninja'
      uses: lukka/run-cmake@v2
      with:
        cmakeListsOrSettingsJson: CMakeListsTxtBasic
        cmakeListsTxtPath: '${{ github.workspace }}/TechProgCITemplate/CMakeLists.txt'
        useVcpkgToolchainFile: false
        buildDirectory: '${{github.workspace}}/TechProgCITemplate/build'
        cmakeAppendedArgs: '-GNinja -DGOOGLE_TEST_DIR=googletest/googletest'
    # Runs a set of commands using the runners shell
    - name: Test
      uses: akhtyamovpavel/ActionGtestReport@v0.0.9
      with:
        exec-path: '${{github.workspace}}/TechProgCITemplate/bin/CTestExe'
        report-path: '${{github.workspace}}/TechProgCITemplate/build/tests/test-report.xml'
        working-directory: '${{github.workspace}}/TechProgCITemplate/build/tests/'
    # Artifact uploading step
    - name: UploadArifacts
      uses: actions/upload-artifact@v1
      with:
        name: Bin
        path: '${{github.workspace}}/TechProgCITemplate/bin'
    - name: UploadArifacts
      uses: actions/upload-artifact@v1
      with:
        name: Lib
        path: '${{github.workspace}}/TechProgCITemplate/lib'  
      
