# Workflow for MIPT TP course

name: CI

# Run actions on master commit / pull request
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# Jobs setup
jobs:
  # Main build and test job
  build-and-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
      with: 
        repository: 'google/googletest'
        path: '${{github.workspace}}/3rdparty/' 
    # Runs a single command using the runners shell
    - run: ls
    - name: Build
      run: echo Hello, world!
    
    - name: 'Run CMake with Ninja'
      uses: lukka/run-cmake@v2
      with:
        cmakeListsOrSettingsJson: CMakeListsTxtBasic
        cmakeListsTxtPath: '${{ github.workspace }}/TechProgCITemplate/CMakeLists.txt'
        useVcpkgToolchainFile: false
        buildDirectory: '${{ runner.workspace }}/ci_build/'
        cmakeAppendedArgs: '-GNinja'
        buildWithCMakeArgs: '-DGOOGLE_TEST_DIR=googletest/googletest' 
        
    # Runs a set of commands using the runners shell
    - name: Test
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    # Artifact uploading step
    - name: UploadArifacts
      run: echo UploadArtifacts
